config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

    resources :posts do
      resources :likes, only: [:create, :destroy]
    end

    root 'posts#index'

    delete 'posts/:id' => 'posts#destroy' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

    validates :title, presence: true
    validates :category, presence: true
    validates :about, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(post_id: params[:post_id]) 
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_action :authenticate_user!, except:[:index]

    def index
        
        if params[:search] == nil
          @posts= Post.all
        elsif params[:search] == ''
          @posts= Post.all
        else
          @posts = Post.where("category LIKE ? ",'%' + params[:search] + '%')
        end

    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)

        @post.user_id = current_user.id

      

        if @post.save
          redirect_to posts_url
        else
          render 'posts/new'
        end
        
    end

    def show
        @post = Post.find(params[:id])
      end

      def edit
        @post = Post.find(params[:id])
    end

    def update
        post = Post.find(params[:id])
        

        if post.update(post_params)
          redirect_to tasks_url
        else
          render 'posts/edit'
        end
    end

    def destroy
      post = Post.find(params[:id])
      post.destroy
      redirect_to action: :index
    end
    
    private
      def post_params
        params.require(:post).permit(:title, :about, :category, :time)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paper2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    

  </head>

  <body> 
  <header class="o-navBar" data-v-9812e696=""><div class="o-navbarTop o-navBar__inner" data-v-52016f29="" data-v-9812e696=""><h1 class="m-siteLogo m-siteLogo--aniv" data-v-a679613e="" data-v-52016f29=""><img src="https://d291vdycu0ht11.cloudfront.net/nuxt/production/img/logo.7501732.svg" alt="note" decoding="async" id="note-logo" class="a-image m-siteLogo__image" data-v-027cc35a="" data-v-a679613e=""><a href="/" target="_self" data-v-a679613e="" class="active a-link m-siteLogo__link fn" data-v-0446330f="" aria-current="page"></a></h1> <nav aria-label="アカウント" class="o-navbarTop__nav" data-v-52016f29=""><!----> <div class="o-navbarTop__navItem" data-v-52016f29=""><div class="o-navbarTop__search" data-v-141e56f5="" data-v-52016f29=""><form action="#" role="search" data-v-141e56f5=""><div class="m-iconWithtext" data-v-5760b2fe="" data-v-141e56f5=""><div class="m-iconWithtext__form" style="display:none;" data-v-5760b2fe=""><div class="m-iconWithtext__field" data-v-5760b2fe=""><input placeholder="キーワードや作者名で検索" type="search" value="" class="m-iconWithtext__fieldInput a-input a-input--width_fit" data-v-189cf910="" data-v-5760b2fe=""></div> <div class="m-iconWithtext__submit" data-v-5760b2fe=""><button type="button" aria-label="検索" class="a-icon a-icon--search a-icon--size_medium" data-v-5760b2fe=""></button></div></div> <div style="display:none;" data-v-5760b2fe=""><!----></div> <div style="display:;" data-v-5760b2fe=""><div class="m-iconWithtext__button" data-v-5760b2fe=""><button type="button" aria-label="検索" class="a-icon a-icon--search a-icon--size_medium" data-v-5760b2fe=""></button></div></div></div></form> <!----> <!----></div></div> <!----> <!----> <!----> <div class="o-navbarTop__navItem o-navbarTop__navItem--login" data-v-52016f29=""><a href="https://note.com/login" target="_self" data-type="none" data-size="small" data-disable-focus="false" class="a-button" data-v-0e52a830="" data-v-52016f29=""><div class="a-button__inner" data-v-0e52a830="">
  ログイン
</div></a></div> <div class="o-navbarTop__navItem o-navbarTop__navItem--entry" data-v-52016f29=""><a href="https://note.com/signup" target="_self" data-type="primary" data-size="small" data-disable-focus="false" class="a-button" data-v-0e52a830="" data-v-52016f29=""><div class="a-button__inner" data-v-0e52a830="">
        新規登録
      </div></a></div></nav></div> <div class="o-navbarMenu o-navBar__inner" data-v-2becd3e6="" data-v-9812e696=""><nav aria-label="全体のコンテンツ" class="o-navbarMenu__menu" data-v-2becd3e6=""><!----> <!----> <a href="/" aria-current="page" class="o-navbarMenu__menuItem active a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium is-active" data-v-baf1a512="">
        話題
      </div></div></a> <a href="/contests" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        募集中
        <span class="o-navbarMenu__notification" data-v-baf1a512="" data-v-2becd3e6="">
          73
        </span></div></div></a> <a href="/circle" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        サークル
      </div></div></a> <a href="/magazine" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        マガジン
      </div></div></a> <a href="/event" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        イベント
      </div></div></a> <a href="/topic/shopping" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        ショッピング
      </div></div></a> <a href="/hashtag" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        人気タグ
      </div></div></a> <a href="/help" class="o-navbarMenu__menuItem a-link" data-v-0e52a830="" data-v-2becd3e6=""><div class="a-navItem" data-v-baf1a512="" data-v-2becd3e6=""><div class="a-navItem__item a-navItem__item--size_medium" data-v-baf1a512="">
        noteをまなぶ
      </div></div></a></nav></div> <!----></header>
    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>

  </body>
</html>

app/views/posts/edit.html.erb
<h1>SenseOfCommitment</h1>
<% if @task.errors.any? %>
  <div>
    <ul style="color: red">
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/posts/index.html.erb
<h1>SenseOfCommitment</h1>
<h3>投稿一覧</h3>

<%= link_to "ログイン", new_user_session_path %>
<%= link_to "新規登録", new_user_registration_path %>

<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>

<h3>投稿を検索</h3>
  <%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
    <%= text_field_tag :search %>
    <%= submit_tag '検索する'  %>
<% end %>

<%= link_to "新規投稿へ", new_post_path %>
<div class="post-container">
  <% @posts.each do |t| %>
    <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= t.title %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= t.category %></h6>
    <p class="card-text"><%= t.about %></p>
    <p class="card-time"><%= t.time %></p>
    <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <i class="fas fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <i class="far fa-heart"></i><%= t.likes.count %>
              <% end %>
          <% end %>
          <% else %>
          <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
          <%= link_to "詳細へ", post_path(t.id) %>
          <%= link_to "編集する", edit_post_path(t.id) %>
          <%= link_to "削除する", post_path(t.id), method: :delete %>
          <%= t.user_id %>
          <%= t.created_at %>
  </div>
</div>
        
        
        
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>SenceOfCommitment</h1>

<% if @post.errors.any? %>
  <div>
    <ul style="color: red">
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h3>Tweet一覧</h3>
<%= form_for @post do |f| %>
  <div class="field">
  <br><%= f.label :title %><br/>
  <%= f.text_field :title, :size => 140 %>
  </div>

  <div class="field">
  <br><%= f.label :category %><br/>
    <%= f.select :category, 
    [["経済", "経済"], 
    ["国際", "国際"], 
    ["スポーツ", "スポーツ"],
    ["宗教", "宗教"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
  <br><%= f.label :about %><br/>
    <%= f.text_field :about, :size => 140 %>
  </div>

  <%= date_field_tag 'post[time]', nil %>

  <%= f.submit "Tweetする" %>
<% end %>

<%= link_to "Tweet一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h1>SenceOfCommitment</h1>
<h3>Tweet詳細</h3>

<div class="post">
  <p><%= @post.title %></p>
  <p><%= @post.category %></p>
  <p><%= @post.about %></p>
  <p><%= @post.time %></p>

<% if user_signed_in? %>
<% if current_user.already_liked?(@post) %>
    <%= link_to post_like_path(@post), method: :delete do %>
      <i class="fas fa-heart"></i><%= @post.likes.count %>
    <% end %>
<% else %>
    <%= link_to post_likes_path(@post), method: :post do %>
      <i class="far fa-heart"></i><%= @post.likes.count %>
    <% end %>
  <% end %>
<% else %>
<i class="far fa-heart"></i><%= @post.likes.count %>
<% end %>

</div>

<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>


<%= link_to "Tweet一覧に戻る", posts_path %>
<%= link_to "編集する", edit_post_path(@post.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>